id = "zed-abaqus"
name = "Abaqus"
version = "0.1.0"
schema_version = 1
authors = ["Moa1er <https://github.com/Moa1er>"]
description = "Abaqus input file (.inp, .inc, .incl) support for Zed"
repository = "https://github.com/Moa1er/zed-abaqus"

[grammars.abaqus]
repository = "https://github.com/Moa1er/zed-abaqus"
rev = "db3cc5110abb033832534912f87e79a082ee1ba4"
path = "tree-sitter-abaqus"
