id = "abaqus"
name = "Abaqus"
version = "0.1.0"
schema_version = 1
authors = ["Moa1er <https://github.com/Moa1er>"]
description = "Abaqus input file (.inp, .inc, .incl) support for Zed"
repository = "https://github.com/Moa1er/zed-abaqus"

[grammars.abaqus]
repository = "https://github.com/Moa1er/zed-abaqus"
rev = "85037ad07cd39dbb4f043146302d139815384c96"
path = "tree-sitter-abaqus"

[language_servers.abaqus-language-server]
languages = ["Abaqus"]

